apiVersion: v1
kind: Service
metadata:
  name: homelab-service
spec:
  selector:
    app: homelab  #pod label
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080  # External port on machine
